### PR TITLE
Remove the cache file when a expire item was required

### PR DESCRIPTION
**Pull request by boekkooi**

### CODE REVIEW

**Comment by boekkooi** [comment]
It looks like the test failed to you the bug fixed in PR #5

**Comment by cryptiklemur** [comment]
This is still failing @boekkooi

**Comment by boekkooi** [comment]
@aequasi Fixed after rebase

**Comment by Nyholm** [comment]
Cool. Thank you!

**Comment by Nyholm** [comment]
I've tagged 0.2.1 with your fix included.

**Pull request merged**
